export const typography_ratio: number = 1.25
export const typography_base: number = 14
export const fontFamily: string = '"Inter", sans-serif'

/******************************************************************************
 * Autogenerated styles. Only modify above this line.
 *****************************************************************************/

export const typography_scale: Array<number> = [
  typography_base * Math.pow((1/typography_ratio), 3),
  typography_base * Math.pow((1/typography_ratio), 2),
  typography_base * Math.pow((1/typography_ratio), 1),
  typography_base,
  typography_base * Math.pow(typography_ratio, 1),
  typography_base * Math.pow(typography_ratio, 2),
  typography_base * Math.pow(typography_ratio, 3),
  typography_base * Math.pow(typography_ratio, 4),
  typography_base * Math.pow(typography_ratio, 5)
]
